services:
  app:
    build: .
    container_name: mongo-crud
    ports:
      - 8080:8080
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/jaydb
    depends_on:
      - mongodb
  #    networks:
  #      - mongo-network

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
#    networks:
#      - mongo-network
volumes:
  mongodb_data: